### ISSUE TITLE
The reply to this interaction has already been sent or deferred.

### ISSUE THREAD

**Issue by vstrg** [3urobeat/steam-comment-bot-discord-plugin#2]
Hey, I started comment process with discord bot and it did not send a message when it was completed 

![293516732-94680365-219a-4617-8f40-c19f18b7be5b](https://github.com/3urobeat/steam-comment-bot-discord-plugin/assets/132234326/e7027509-732d-4d7c-ba57-7e117a599b22)

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue!  
This is an oopsie - looks like it is trying to send multiple messages for one interaction (which makes sense ofc, stupid from me to not have that realized earlier).  

I sadly cannot fix that right now because the bot does not have an automatic way for updating plugins yet (without a version bump).  
This is something I want to address in v2.15.  

I'll leave this issue open and will update it if I have something to share

**Comment by 3urobeat** [comment]
Version 1.0.2 is now out which fixes this issue.  
Version 2.15.0 of the bot will include a auto plugin update system (it's already out on the beta-testing branch), so this plugin will automatically update.  

I'll close this issue already now so that I won't forget it.
